### ISSUE TITLE
Hey can't open zip file

### ISSUE THREAD

**Issue by hardcorehunter** [LordScout/SonicEXE-master#2]
IT wouldn't let me open the zip file how do i fix it

**Comment by LordScout** [comment]
are you using winrar?

**Comment by hardcorehunter** [comment]
no i'm using a chromebook it opens zip file but not this one
________________________________

**Comment by LordScout** [comment]
you're going to the releases page right? you're not just downloading the
source code?

**Comment by hardcorehunter** [comment]
I did download it from the releases page not the source code.
________________________________

**Comment by hardcorehunter** [comment]
yeah it was chrome os for some odd reason the file download too fast so i think chrome os couldn't download at once which led the zip to be corrputed but now i have windows 10 it works fine so i think it's chrome os that cause the problem also good job man on this it's good.
